### ISSUE TITLE
Need to contact you

### ISSUE THREAD

**Issue by mugesh-kanna** [IulianEmilTampu/OCT_thyroid_DL_classification#1]
Hi IulianEmilTampu, Due to my study I have some doubts regarding this projects. How can I contact you?

**Comment by IulianEmilTampu** [comment]
Hi, 
Please let me know using this issue thread what are your doubts about the project.
Best, 
Iulian

**Comment by mugesh-kanna** [comment]
I didn't find the dataset and I need deep guidance in this project. Can u help me

**Comment by IulianEmilTampu** [comment]
Please follow the links available in this publication (https://onlinelibrary.wiley.com/doi/full/10.1002/jbio.202200227) to obtain the datasets that are open-access. Regarding the use of the code, the scripts and the repository contain the information on how to run them.

Best, 
Iulian

**Comment by mugesh-kanna** [comment]
ok I try my best. If I got any doubts i will reach you. Thank You so much Iulian.

**Comment by mugesh-kanna** [comment]
Hi Iulian, where i can find these file 'that the .csv file describing the classification of every volume is available'?

**Comment by mugesh-kanna** [comment]
I need your help Iulian!

**Comment by IulianEmilTampu** [comment]
Issue closed due to inactivity.
